# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: composer:2.0


pipelines:
  default:
    - parallel:
        - step:
            name: test
            script:
              - pwd
              - cd tests
              - composer install
              - ./vendor/bin/hyper-run -S 0.0.0.0:80 -s 0.0.0.0:443 -t . &
              - sleep 20
              - php run.php -hlocalhost -p
            caches:
              - composer
